---
- name: "dhcpd | Check if the /etc/apparmor.d/local folder exists"
  ansible.builtin.stat:
    path: "{{ hostvars[inventory_hostname]['dhcpd_apparmor_dest'] }}"
  register: "apparmor_local"
- name:
    "dhcpd | Allow AppArmor access to temporary ansible files for validation"
  ansible.builtin.copy:
    src: "apparmor/usr.sbin.dhcpd"
    dest: "/etc/apparmor.d/local/usr.sbin.dhcpd"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - "apparmor_local.stat.exists"
  notify:
    - "Restart apparmor"
- name: "dhcpd | Enable apparmor"
  ansible.builtin.service:
    name: "{{ hostvars[inventory_hostname]['dhcpd_apparmor_service'] }}"
    state: "started"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['dhcpd_apparmor_enable'] is defined"
    - "hostvars[inventory_hostname]['dhcpd_apparmor_enable'] == 'true'"
- meta: "flush_handlers"
