---
- name: "dhcpd | Install the required packages in Redhat derivatives"
  ansible.builtin.dnf:
    name: "{{ hostvars[inventory_hostname]['dhcpd_server_package'] }}"
    state: "present"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
- name: "dhcpd | Install the required packages in Debian derivatives"
  ansible.builtin.apt:
    name: "{{ hostvars[inventory_hostname]['dhcpd_server_package'] }}"
    state: "present"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
- name: "dhcpd | Install the required packages in ArchLinux derivatives"
  community.general.pacman:
    name: "{{ hostvars[inventory_hostname]['dhcpd_server_package'] }}"
    state: "present"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
