---
- name: Restart apparmor
  ansible.builtin.service:
    name: "{{ hostvars[inventory_hostname]['dhcpd_apparmor_service'] }}"
    state: "restarted"
  when:
  - "hostvars[inventory_hostname]['dhcpd_apparmor_restart'] is defined"
  - "hostvars[inventory_hostname]['dhcpd_apparmor_restart'] == 'true'"
- name: Restart dhcpd
  ansible.builtin.service:
    name: "{{ hostvars[inventory_hostname]['dhcpd_dhcpd_service'] }}"
    state: "restarted"
  when:
  - "hostvars[inventory_hostname]['dhcpd_service_restart'] is defined"
  - "hostvars[inventory_hostname]['dhcpd_service_restart'] == 'true'"
