---
- name: "dhcpd | Start 'dhcpd_groups' validation"
  ansible.builtin.include_tasks:
    file: "netaddr_validation.yml"
  loop: "{{ vars['dhcpd_group_names'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  when:
    - "vars['dhcpd_group_names'] is defined"
    - "vars['dhcpd_group_names'] != []"
- name: "dhcpd | Start 'dhcpd_hosts' validation"
  ansible.builtin.include_tasks:
    file: "netaddr_validation_simple.yml"
  loop: "{{ hostvars[inventory_hostname]['dhcpd_hosts'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  when:
    - "hostvars[inventory_hostname]['dhcpd_hosts'] is defined"
    - "hostvars[inventory_hostname]['dhcpd_hosts'] != ''"
- name: "dhcpd | Start 'dhcpd_global_hosts' validation"
  ansible.builtin.include_tasks:
    file: "netaddr_validation_simple.yml"
  loop: "{{ hostvars[inventory_hostname]['dhcpd_global_hosts'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  when:
    - "hostvars[inventory_hostname]['dhcpd_global_hosts'] is defined"
    - "hostvars[inventory_hostname]['dhcpd_global_hosts'] != ''"
