---
- ansible.builtin.debug:
    msg: "Start 'dhcpd_groups' validation"
  when:
    - "vars['dhcpd_group_names'] is defined"
    - "vars['dhcpd_group_names'] != []"
- include_tasks: "netaddr_validation.yml"
  loop: "{{ vars['dhcpd_group_names'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  when:
    - "vars['dhcpd_group_names'] is defined"
    - "vars['dhcpd_group_names'] != []"
- ansible.builtin.debug:
    msg: "Start 'dhcpd_hosts' validation"
  when:
    - "hostvars[inventory_hostname]['dhcpd_hosts'] is defined"
    - "hostvars[inventory_hostname]['dhcpd_hosts'] != ''"
- include_tasks: "netaddr_validation_simple.yml"
  loop: "{{ hostvars[inventory_hostname]['dhcpd_hosts'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  when:
    - "hostvars[inventory_hostname]['dhcpd_hosts'] is defined"
    - "hostvars[inventory_hostname]['dhcpd_hosts'] != ''"
- ansible.builtin.debug:
    msg: "Start 'dhcpd_global_hosts' validation"
  when:
    - "hostvars[inventory_hostname]['dhcpd_global_hosts'] is defined"
    - "hostvars[inventory_hostname]['dhcpd_global_hosts'] != ''"
- include_tasks: "netaddr_validation_simple.yml"
  loop: "{{
    hostvars[inventory_hostname]['dhcpd_global_hosts'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  when:
    - "hostvars[inventory_hostname]['dhcpd_global_hosts'] is defined"
    - "hostvars[inventory_hostname]['dhcpd_global_hosts'] != ''"
