---
- name: dhcpd | Assert that fixed address is ip address
  assert:
    that: "outer_item.fixed_address | ipaddr()"
    msg: "{{ outer_item.name ~ ' is not ipaddr: ' ~ outer_item.fixed_address }}"
    quiet: "true"
  loop_control:
    label: "{{ outer_item.name }}"
  when:
  - "outer_item.fixed_address is defined"
  - "outer_item.fixed_address != ''"
- name: dhcpd | Assert that broadcast address is ip address
  assert:
    that: "outer_item.broadcast_address | ipaddr()"
    msg: "{{ outer_item.name ~ ' is not ipaddr: ' ~
             outer_item.broadcast_address }}"
    quiet: "true"
  loop_control:
    label: "{{ outer_item.name }}"
  when:
  - "outer_item.broadcast_address is defined"
  - "outer_item.broadcast_address != ''"
- name: dhcpd | Assert that mac address is hardware address in linux format
  assert:
    that: "outer_item.mac_address | hwaddr('linux')"
    msg: "{{ outer_item.name ~ ' is not maddr: ' ~ outer_item.mac_address }}"
    quiet: "true"
  loop_control:
    label: "{{ outer_item.name }}"
  when:
  - "outer_item.mac_address is defined"
  - "outer_item.mac_address != ''"
